### ISSUE TITLE
Need clarifications

### ISSUE THREAD

**Issue by SamBlaise** [zxqfl/mcts#1]
Hi,
I don't know if you still want to worry about this project but, if you are ever available, I would like to have some clarifications to use your library whose API is nice.

I'm not a MCTS pro, but the function: 
```evaluate_new_state``` 
is to evaluate all the possible new states of a node?

If you ever have time maybe you could upgrade the dependencies to update the codebase.

Thanks for your library.

**Comment by zxqfl** [comment]
Hi Sam,

`evaluate_new_state` should evaluate only the given state, not the possible future states. There are separate `evaluate_new_state` and `evaluate_existing_state` functions in case your evaluation is non-deterministic (eg. if it involves rollouts). If your evaluation is deterministic, you should do all your evaluation in `evaluate_new_state` and write `evaluate_existing_state` to simply return the existing evaluation.
